---
title: "Progeny analysis between Zambia and U.S. cohorts"
output: html_notebook
---

```{r}
library(Seurat)
library(tidyverse)
```

```{r}
combined = readRDS("combined_iterate_jan13.rds")
```

```{r}
combined_duo = subset(combined,region=="Duodenum") %>% subset(HIV.HTLV.=="N")
```

# Progeny

```{r}
epi_progeny = readRDS("figures/epi_progeny.rds")
```

```{r}
tnk_progeny = readRDS("figures/t_cell_progeny.rds")
```

```{r}
get_all_way = function(sobj,meta){
    sobj_test = subset(sobj, study %in% c("EoE","EE"))
    results_eoe = get_sobj_progeny_two_way(sobj_test,"study")
    sobj_west = subset(sobj,study %in% c("EE","Resection"))
    results_whipple = get_sobj_progeny_two_way(sobj_west,"study")
    sobj$study[sobj$study=="Resection"] = "not EE"
    sobj$study[sobj$study=="EoE"] = "not EE"
    results_all =get_sobj_progeny_two_way(sobj,"study")
    results_all = cbind(results_all,results_eoe,results_whipple)
    results_all = results_all[,-c(1,3,5)]
    colnames(results_all) = c("adj_pval_all","adj_pval_eoe","adj_pval_whipple")
    return(results_all[order(rowSums(results_all),decreasing=F),])
}

get_sobj_progeny_two_way = function(sobj,meta){
    
    # initialize matrix for pvalues
    meta="study"
    pvals = matrix(1, nrow=14,ncol=3)
    temp = GetAssayData(sobj,assay="progeny",slot="data")
    rownames(pvals) = rownames(temp)
    colnames(pvals) = c("pval","p_val_adj","sign") #1 if mean higher in EE, -1 if mean lower in EE

    for(i in 1:14){ # loop thru pathways
        pvals[i,1] = wilcox.test(temp[i,sobj[[meta]][,1]=="EE"],temp[i,sobj[[meta]][,1]!="EE"])$p.value
        if(mean(temp[i,sobj[[meta]][,1]=="EE"])>mean(temp[i,sobj[[meta]][,1]!="EE"])){
            pvals[i,3] = 1
        }else{
            pvals[i,3] = -1
        }
    }
    pvals[,2] = p.adjust(pvals[,1],method="BH")
    return(as.data.frame(pvals))

}

combine_markers = function(markers_all,markers_eoe,markers_wp,sig_threshold=0.05){
  sig_all = rownames(markers_all)[markers_all$p_val_adj < sig_threshold]
  marker_bools = as.vector(sapply(sig_all,function(x){check_marker(x,markers_eoe,markers_wp,0.5)}))
  sig_all = sig_all[marker_bools]
  return(markers_all[sig_all,])
}

check_marker = function(marker,markers_eoe,markers_wp,sig_threshold=0.5){
  in_eoe = marker %in% rownames(markers_eoe)[markers_eoe$p_val_adj < sig_threshold]
  in_wp = marker %in% rownames(markers_wp)[markers_wp$p_val_adj < sig_threshold]
  if(in_eoe & in_wp){
    if(sign(markers_eoe[marker,]$sign)==sign(markers_wp[marker,]$sign)){
      return(TRUE)
    }else{
        return(FALSE)
    }
  }else{
    return(FALSE)
  }
}


```

```{r}
get_progeny_for_cell_type = function(sobj){

    CellsDiseases <- data.frame(Cell = names(Idents(sobj)), 
        cellType = as.character(sobj$study),
        stringsAsFactors = FALSE)
    ## We transform Progeny scores into a data frame to better handling the results
    progeny_scores_df <- 
        as.data.frame(t(GetAssayData(sobj, slot = "scale.data", 
            assay = "progeny"))) %>%
        rownames_to_column("Cell") %>%
        gather(Pathway, Activity, -Cell) 

    ## We match Progeny scores with the cell clusters.
    progeny_scores_df <- inner_join(progeny_scores_df, CellsDiseases)
    ## We summarize the Progeny scores by cellpopulation
    summarized_progeny_scores <- progeny_scores_df %>% 
        group_by(Pathway, cellType) %>%
        summarise(avg = mean(Activity), std = sd(Activity))

    cohenD = c()
    for(i in 1:nrow(summarized_progeny_scores)){
        if(i %% 2 ==0){
            cohenD = c(cohenD, (summarized_progeny_scores$avg[i-1]-summarized_progeny_scores$avg[i])/(sqrt((summarized_progeny_scores$std[i-1]^2 + summarized_progeny_scores$std[i]^2)/2)))
        }
    }

    return(tibble(Pathway=unique(summarized_progeny_scores$Pathway),cohensD=cohenD))
}  
#     # Calculates EE score - not EE score for each pathway
# summarized_progeny_scores_minus <- summarized_progeny_scores %>%
#     group_by(Pathway) %>%
#     mutate(diff = -1*(avg - lag(avg, default = first(avg)))) %>%
#     summarise(delta=sum(diff))

# summarized_progeny_scores_cohen <- summarized_progeny_scores %>%
#     group_by(Pathway) %>%
#     mutate(diff = -1*((avg - lag(avg, default = first(avg)))))



#     summarise(delta=sum(diff))
    
#     return(summarized_progeny_scores)
# }
```

```{r}
cell_types = c("Monocytes","Macrophages","Plasma cells")
subset_tiers = c(2,2,2)
```

```{r}
i=1
type = cell_types[i]
# Prepping Seurat Object
if(subset_tiers[i]==2){
    sobj = subset(combined_duo,tier2==type)
}else{
    sobj = subset(combined_duo,tier3==type)
}
DefaultAssay(sobj) <- "progeny"
Idents(sobj)<-"study"
sobj_eoe = subset(sobj,study!="Eesection")
sobj_wp = subset(sobj,study!="EoE")
sobj$study[sobj$study=="EoE"]="not EE"
sobj$study[sobj$study=="Resection"]="not EE"

# Getting delta between EE & not EE scores over pathways
prog_scores = get_progeny_for_cell_type(sobj)
prog_scores$pvalue = 1
prog_scores = prog_scores %>% add_column(cell_type =rep(type,nrow(prog_scores)),.before=T)

# Calculating significant pathways
markers.vs.all = get_sobj_progeny_two_way(sobj,"study")
markers.vs.eoe = get_sobj_progeny_two_way(sobj_eoe,"study")
markers.vs.wp = get_sobj_progeny_two_way(sobj_wp,"study")
combined_markers = combine_markers(markers.vs.all,markers.vs.eoe,markers.vs.wp)

for(i in 1:nrow(combined_markers)){
    prog_scores$pvalue[prog_scores$Pathway == rownames(combined_markers)[i]] = combined_markers$p_val_adj[i]
}
final_prog = prog_scores
```

```{r}
for(i in 2:length(cell_types)){
    type = cell_types[i]
    print(type)
    # Prepping Seurat Object
    print(subset_tiers[i])
    if(subset_tiers[i]==2){
        sobj = subset(combined_duo,tier2==type)
    }else{
        sobj = subset(combined_duo,tier3==type)
    }
    DefaultAssay(sobj) <- "progeny"
    Idents(sobj)<-"study"
    sobj_eoe = subset(sobj,study!="Resection")
    sobj_wp = subset(sobj,study!="EoE")
    sobj$study[sobj$study=="EoE"]="not EE"
    sobj$study[sobj$study=="Resection"]="not EE"
    
    # Getting delta between EE & not EE scores over pathways
    prog_scores = get_progeny_for_cell_type(sobj)
    prog_scores$pvalue = 1
    prog_scores = prog_scores %>% add_column(cell_type =rep(type,nrow(prog_scores)),.before=T)
    
    # Calculating significant pathways
    markers.vs.all = get_sobj_progeny_two_way(sobj,"study")
    markers.vs.eoe = get_sobj_progeny_two_way(sobj_eoe,"study")
    markers.vs.wp = get_sobj_progeny_two_way(sobj_wp,"study")
    combined_markers = combine_markers(markers.vs.all,markers.vs.eoe,markers.vs.wp)
    
    for(i in 1:nrow(combined_markers)){
        prog_scores$pvalue[prog_scores$Pathway == rownames(combined_markers)[i]] = combined_markers$p_val_adj[i]
    }
    
    final_prog = rbind(final_prog,prog_scores)
}
```

```{r}
saveRDS(final_prog,"figures/bms_progeny.rds")
```

```{r}
bms_progeny = readRDS("figures/bms_progeny.rds")
```

```{r}
final_progeny = rbind(epi_progeny,tnk_progeny,bms_progeny)
```

```{r}
colnames(final_progeny)[4] ="p_val_adj"
final_progeny = final_progeny %>% filter(p_val_adj < 0.05)
```

```{r}
write.csv(final_progeny,"final_progeny.csv")
```


```{r}
head(final_progeny)
```



# Dorothea
```{r}
epi_doro = readRDS("figures/epi_dorothea.rds")
tnk_doro = readRDS("figures/t_cell_dorothea.rds")
```

```{r}
combine_markers = function(markers_all,markers_eoe,markers_wp,sig_threshold=0.05){
  sig_all = rownames(markers_all)[markers_all$p_val_adj < sig_threshold]
  marker_bools = as.vector(sapply(sig_all,function(x){check_marker(x,markers_eoe,markers_wp,0.5)}))
  sig_all = sig_all[marker_bools]
  return(markers_all[sig_all,])
}

check_marker = function(marker,markers_eoe,markers_wp,sig_threshold=0.5){
  in_eoe = marker %in% rownames(markers_eoe)[markers_eoe$p_val_adj < sig_threshold]
  in_wp = marker %in% rownames(markers_wp)[markers_wp$p_val_adj < sig_threshold]
  if(in_eoe & in_wp){
    if(sign(markers_eoe[marker,]$sign)==sign(markers_wp[marker,]$sign)){
      return(TRUE)
    }else{
      return(FALSE)
    }
  }else{
    return(FALSE)
  }
}

get_sobj_dorothea_two_way = function(sobj,meta){
  
  # initialize matrix for pvalues
  meta="study"
  pvals = matrix(1, nrow=292,ncol=3)
  temp = GetAssayData(sobj,assay="dorothea",slot="data")
  rownames(pvals) = rownames(temp)
  colnames(pvals) = c("pval","p_val_adj","sign") #1 if mean higher in EE, -1 if mean lower in EE
  
  for(i in 1:292){ # loop thru pathways
    pvals[i,1] = wilcox.test(temp[i,sobj[[meta]][,1]=="EE"],temp[i,sobj[[meta]][,1]!="EE"])$p.value
    if(mean(temp[i,sobj[[meta]][,1]=="EE"])>mean(temp[i,sobj[[meta]][,1]!="EE"])){
      pvals[i,3] = 1
    }else{
      pvals[i,3] = -1
    }
  }
  pvals[,2] = p.adjust(pvals[,1],method="BH")
  return(as.data.frame(pvals))
  
}

generate_markers = function(sobj,sig_threshold = 0.05){
  DefaultAssay(sobj) <- "dorothea"
  Idents(sobj)<-"study"
  sobj_eoe = subset(sobj,study!="Resection")
  sobj_wp = subset(sobj,study!="EoE")
  sobj$study[sobj$study=="EoE"]="not EE"
  sobj$study[sobj$study=="Resection"]="not EE"
  markers.vs.all = get_sobj_dorothea_two_way(sobj,"study")
  markers.vs.eoe = get_sobj_dorothea_two_way(sobj_eoe,"study")
  markers.vs.wp = get_sobj_dorothea_two_way(sobj_wp,"study")
  combined_markers = combine_markers(markers.vs.all,markers.vs.eoe,markers.vs.wp,sig_threshold)
  return(combined_markers)
}

```

```{r}
get_dorothea_for_cell_type = function(sobj){
    viper_scores_df <- GetAssayData(sobj, slot = "scale.data",  assay = "dorothea") %>% data.frame() %>% t()

    CellsClusters <- data.frame(cell = names(Idents(sobj)), 
                              study = as.character(sobj$study),
                              stringsAsFactors = FALSE)

    viper_scores_clusters <- viper_scores_df  %>% data.frame() %>% rownames_to_column("cell") %>% gather(tf, activity, -cell) %>% inner_join(CellsClusters)
    summarized_viper_scores <- viper_scores_clusters %>% 
    group_by(tf, study) %>%
    summarise(avg = mean(activity),
              std = sd(activity))
    
    cohenD = c()
    for(i in 1:nrow(summarized_viper_scores)){
        if(i %% 2 ==0){
            cohenD = c(cohenD, (summarized_viper_scores$avg[i-1]-summarized_viper_scores$avg[i])/(sqrt((summarized_viper_scores$std[i-1]^2 + summarized_viper_scores$std[i]^2)/2)))
        }
    }

    return(tibble(tf=unique(summarized_viper_scores$tf),cohensD=cohenD))
    
    
#     summarized_viper_scores <- summarized_viper_scores %>%
#         group_by(tf) %>%
#         mutate(diff = -1*(avg - lag(avg, default = first(avg)))) %>%
#         summarise(delta=sum(diff))
#     return(summarized_viper_scores)
}
```

```{r}
cell_types = c("Myeloid","B cells")
subset_tiers = c(1,1)
i=1
type = cell_types[1]
# Prepping Seurat Object
if(subset_tiers[i]==2){
    sobj = subset(combined_duo,tier2==type)
}else{
    sobj = subset(combined_duo,tier1==type)
}
DefaultAssay(sobj) <- "dorothea"
Idents(sobj)<-"study"
sobj <- ScaleData(sobj,verbose=F)
sobj_eoe = subset(sobj,study!="Resection")
sobj_wp = subset(sobj,study!="EoE")
sobj$study[sobj$study=="EoE"]="not EE"
sobj$study[sobj$study=="Resection"]="not EE"

# Getting delta between EE & not EE scores over tfs
doro_scores = get_dorothea_for_cell_type(sobj)
doro_scores$pvalue = 1
doro_scores = doro_scores %>% add_column(cell_type =rep(type,nrow(doro_scores)),.before=T)

# Calculating significant tfs
markers.vs.all = get_sobj_dorothea_two_way(sobj,"study")
markers.vs.eoe = get_sobj_dorothea_two_way(sobj_eoe,"study")
markers.vs.wp = get_sobj_dorothea_two_way(sobj_wp,"study")
combined_markers = combine_markers(markers.vs.all,markers.vs.eoe,markers.vs.wp)

for(i in 1:nrow(combined_markers)){
    doro_scores$pvalue[doro_scores$tf == rownames(combined_markers)[i]] = combined_markers$p_val_adj[i]
}
final_doro = doro_scores

for(i in 2:length(cell_types)){
    type = cell_types[i]
    print(type)
    # Prepping Seurat Object
    if(subset_tiers[i]==2){
        sobj = subset(combined_duo,tier2==type)
    }else{
        sobj = subset(combined_duo,tier1==type)
    }
    DefaultAssay(sobj) <- "dorothea"
    Idents(sobj)<-"study"
    sobj <- ScaleData(sobj,verbose=F)
    sobj_eoe = subset(sobj,study!="Resection")
    sobj_wp = subset(sobj,study!="EoE")
    sobj$study[sobj$study=="EoE"]="not EE"
    sobj$study[sobj$study=="Resection"]="not EE"

    # Getting delta between EE & not EE scores over tfs
    doro_scores = get_dorothea_for_cell_type(sobj)
    doro_scores$pvalue = 1
    doro_scores = doro_scores %>% add_column(cell_type =rep(type,nrow(doro_scores)),.before=T)

    # Calculating significant tfs
    markers.vs.all = get_sobj_dorothea_two_way(sobj,"study")
    markers.vs.eoe = get_sobj_dorothea_two_way(sobj_eoe,"study")
    markers.vs.wp = get_sobj_dorothea_two_way(sobj_wp,"study")
    combined_markers = combine_markers(markers.vs.all,markers.vs.eoe,markers.vs.wp)

    for(i in 1:nrow(combined_markers)){
        doro_scores$pvalue[doro_scores$tf == rownames(combined_markers)[i]] = combined_markers$p_val_adj[i]
    }
    
    final_doro = rbind(final_doro,doro_scores)
}
```

```{r}
bms_doro = final_doro
saveRDS(bms_doro,"figures/bms_dorthea.rds")
```

```{r}
final_dorothea = rbind(epi_doro,tnk_doro,bms_doro)
```
```{r}
colnames(final_dorothea)[4] = "p_val_adj"
```

```{r}
final_dorothea = final_dorothea %>% filter(p_val_adj < 0.05)
write.csv(final_dorothea,"cleaned_dorothea.csv")
```

```{r}
table(subset(combined_duo, tier4 =="T CD8 CD69 GZMH")$orig.ident)
```


```{r}
# writing the durban results as a csv
durban_prog = readRDS("../durban/progeny_dorothea/progeny_epi.rds")
```

```{r}
write.csv(durban_prog,"durban_progeny.csv")
```

```{r}
durban_doro = readRDS("../durban/progeny_dorothea/dorothea_epi.rds")
write.csv(durban_doro,"durban_dorothea.csv")
```



