---
title: "NicheNet: Zambia vs all other cohorts"
output: html_notebook
---

```{r}
library(Seurat)
library(tidyverse)
library(nichenetr)
library(viridis)
```

```{r}
combined= readRDS("durban_ee_eoe_resection_june152021.rds")
```

```{r}
combined_duo = subset(combined,region=="Duodenum") %>% subset(HIV.HTLV.=="N")
```

# Running NicheNet

```{r}
source("nichenet_helper_functions.R")
```


```{r}
ligand_target_matrix = readRDS("../reseq_analysis/nichenet/ligand_target_matrix.rds")
lr_network = readRDS(url("https://zenodo.org/record/3260758/files/lr_network.rds"))
weighted_networks = readRDS(url("https://zenodo.org/record/3260758/files/weighted_networks.rds"))
weighted_networks_lr = weighted_networks$lr_sig %>% inner_join(lr_network %>% distinct(from,to), by = c("from","to"))
```


```{r}
de_files = list.files("DE/combined_DE_passed_filter/")
```

```{r}
# Some DE files are empty tables, remove those
use_de = de_files[c(1:3,5,7,9,10,11,13,14,15,17,19,20,23,24,26,27,29,31)]
use_de
```

```{r}
# Building the marker gene table
i = 1
cell_type = get_cell_subset_name(use_de[i])
markers = read.csv(paste0("DE/combined_DE_passed_filter/",use_de[i]),row.names = 1)
markers$cluster = cell_type
final_markers = markers

for(i in 2:length(use_de)){
  cell_type = get_cell_subset_name(use_de[i])
  markers = read.csv(paste0("DE/combined_DE_passed_filter/",use_de[i]),row.names = 1)
   if(nrow(markers)>0){
      markers$cluster = cell_type
      final_markers = rbind(final_markers,markers)
  }
}
```

```{r}
# Subsetting seurat object down to to only cell tyupes with sig. DE genes
combined_duo$cell_types = ""
for(i in 1:length(use_de)){
  cell_type = get_cell_subset_name(use_de[i])
  use_tier = get_tier_for_sobj(use_de[i])
  combined_duo$cell_types[combined_duo@meta.data[,use_tier]==cell_type] = cell_type
}
combined_duo_nichenet = subset(combined_duo,cell_types!="")
# and then also filter down to the stuff where we actually got useful DE results
combined_duo_nichenet = subset(combined_duo_nichenet,cell_types %in% unique(final_markers$cluster))
Idents(combined_duo_nichenet) <- "cell_types"
```


```{r}
final_markers$cluster = final_markers$cell_type
```


```{r}
final_cell_types = unique(combined_duo_nichenet$cell_types)
for(i in 1:length(final_cell_types)){
  cell_type = final_cell_types[i]
  print(cell_type)
  r = cell_type
  s= final_cell_types[final_cell_types!=r]
  data_all = run_nichenet_data(combined_duo_nichenet,r,s,final_markers)
  saveRDS(data_all,paste0("nichenet_data/",cell_type,"_nichenet.rds"))
}
```



# Plotting Nichenet


```{r}
list.files("nichenet_data/")
```


```{r}
# Summarizing the pearson correaltions between ligand induced gene expression signature
# and cell type DE for each cell type with significant DE

data_types = c("Stem OLFM4 LGR5","Stem OLFM4","Stem cycling","Ent APOA ALPI","Goblet","T CD8 CD69hi","T CD8 CCL5hi CD6hi","T CD4 CD69lo","T MT","B cells","Monocytes","Macrophages")
data_files = list()
for(i in 1:length(data_types)){
    data_files[[i]] = readRDS(paste0("nichenet_data/",data_types[i],"_nichenet.rds"))
}

i = 1
pearson_activities = as_tibble(data_files[[i]][[1]],rownames = "gene")
colnames(pearson_activities) = c("gene",data_types[i])

for(i in 2:length(data_files)){
    temp = as_tibble(data_files[[i]][[1]],rownames = "gene")
    colnames(temp) = c("gene",data_types[i])

    pearson_activities = pearson_activities %>% full_join(temp,by="gene")
}

pearson_zeros = pearson_activities
pearson_zeros[is.na(pearson_zeros)] = 0

pearson_matrix = as.matrix(pearson_zeros[,-1])
rownames(pearson_matrix) = pearson_zeros$gene

ligand_order_hclust =hclust(dist(pearson_matrix,method="euclidean"),method='ward.D')$order

pearson_plot_table = gather(pearson_zeros,key="cell_type",value="pearson",-gene)
pearson_plot_table$gene = factor(pearson_plot_table$gene,levels=rownames(pearson_matrix)[ligand_order_hclust])

```



```{r}
# Reformatting the signifcant DE reuslts
i = 1
de_lfc = as_tibble(data_files[[i]][[4]],rownames = "gene")
de_lfc = de_lfc[,-2]
de_lfc = as.data.frame(de_lfc)
for(j in 3:15){
  de_lfc[,j] = as.numeric(de_lfc[,j])
}


for(i in 2:length(data_files)){
    temp = as_tibble(data_files[[i]][[4]],rownames = "gene")
    temp = temp[,-2]
    temp = as.data.frame(temp)
    for(j in 3:ncol(temp)){
      temp[,j] = as.numeric(temp[,j])
    }

    
    de_lfc = de_lfc %>% full_join(temp)
}

de_zeros = de_lfc
de_zeros[is.na(de_zeros)] = 0
de_zeros = de_zeros[-nrow(de_zeros),]


de_matrix = as.matrix(de_zeros[,-1])
rownames(de_matrix) = de_zeros$gene

ligand_order_hclust = hclust(dist(de_matrix,method="euclidean"),method='ward.D')$order

de_plot_table = gather(de_zeros,key="cell_type",value="de",-gene,-cell_type)
de_plot_table$gene = factor(de_plot_table$gene,levels=rownames(de_matrix)[ligand_order_hclust])
```

```{r}
# Finding the signifcant DE results
de_plot_sig = de_plot_table %>% filter(de!=0)
de_plot_sig$cell_type = gsub("[.]"," ",de_plot_sig$cell_type)
de_plot_sig$cell_type = factor(de_plot_sig$cell_type,levels=final_cell_types)
ggplot(de_plot_sig,aes(x=cell_type,y=gene,fill=de)) +
    geom_tile() + theme_classic() + scale_fill_viridis(option="magma") +
    xlab("Sender Cell Type") + ylab("Prioritized Ligands") + ggtitle("LogFold Change of Differentially\n Expressed Ligands in Sender Cells")+
    labs(fill="Log Fold Change")+
    theme(axis.text.x = element_text(angle=45,hjust=1,size=4),
         axis.text.y=element_text(size=12),legend.text=element_text(size=12),
         legend.title=element_text(size=4),plot.title=element_text(size=6),
         axis.title.y=element_text(size=6),axis.title.x=element_text(size=6)) 

de_plot_0.1 = de_plot_sig %>% filter(abs(de)>0.1)
unique_genes = unique(pearson_plot_table$gene)
unique_genes = unique_genes[unique_genes %in% unique(de_plot_0.1$gene)]
unique_genes = as.character(unique_genes)
grouped_ligands = c("IFNG","TNFSF15","CCL25","CXCL16",
                    "LTB","CD6","CD2","PTPRC","FASLG","CEACAM1",
                    "VEGFA","FGF23","NPNT")
unique_genes = factor(unique_genes,levels=grouped_ligands)
```


# Plotting nichenet results

```{r}

```


```{r}
library(scales)
```
```{r}
pearson_plot_final = pearson_plot_table %>% filter(gene %in% unique_genes)
pearson_plot_final$cell_type = as.character(pearson_plot_final$cell_type)
pearson_plot_final$cell_type = factor(pearson_plot_final$cell_type,levels=data_types)
pearson_plot_final$gene =  factor(pearson_plot_final$gene,levels=rev(grouped_ligands))
# pearson_plot_final = pearson_plot_final %>% filter(pearson > 0.05)
pdf("~/zambia_eed_figures/three_cohorts/nichenet/pearson_correlations.pdf",useDingbats = F,width=5.5,height=5)
ggplot(pearson_plot_final,aes(x=cell_type,y=gene,fill=pearson)) +
    geom_tile() + theme_classic() + 
    scale_fill_gradient(low = "#e1eec3", high = "#f05053") +
    xlab("Receiver Cell Type") + ylab("Prioritized Ligands") + ggtitle("Correlations between ligand signatures\nand EE receiver cell DE genes")+
    labs(fill="Pearson Correlation\n between ligand\n signature and\n EE receiver cell\n DE genes")+
    theme(axis.text.x = element_text(angle=45,hjust=1,size=8),
         axis.text.y=element_text(size=8),
         legend.title=element_text(size=8),
         axis.title.x=element_text(size=12),
         axis.title.y=element_text(size=12),
         plot.title=element_text(size=12))
dev.off()
```


```{r}
pdf("~/zambia_eed_figures/three_cohorts/nichenet/dotplot.pdf",useDingbats = F,width=5.5,height=5)
ligs_for_dotplot = rev(grouped_ligands)
ligs_for_dotplot_adapted = gsub("[.]","-",ligs_for_dotplot)

rotated_dotplot = DotPlot(only_ligand_sobj, features = ligs_for_dotplot_adapted %>% rev()) + coord_flip() + theme(legend.text = element_text(size = 10), legend.title = element_text(size = 12)) # flip of coordinates necessary because we want to show ligands in the rows when combining all plots

rotated_dotplot + theme(axis.text.x = element_text(angle=45,hjust=1,size=5),
                        axis.text.y=element_text(size=6),
                        axis.title.y=element_text(size=11),
                        axis.title.x=element_text(size=11),
                        plot.title=element_text(size=13,face="plain"),
                        legend.title=element_text(size=6),
                       legend.position="right") + scale_size_area(max_size=1.5)+
    ylab("Sender Cell Type") + xlab("Prioritized Ligands") +
    ggtitle("Expression of prioritized\n ligands across cell types") 
dev.off()
```

```{r}
de_plot_table$cell_type = gsub("[.]"," ",de_plot_table$cell_type)
```

```{r}
# reordering cell type names
de_types = final_cell_types[c(12,16,17,10,13,19,15,11,14,18,3,6,4,5,2,1,7,8,9)]
```


```{r}
pdf("~/zambia_eed_figures/three_cohorts/nichenet/ligand_fold.pdf",useDingbats = F,width=5.5,height=5)
de_plot_sig = de_plot_table %>% filter(de!=0)
de_plot_sig$cell_type = gsub("[.]"," ",de_plot_sig$cell_type)
de_plot_sig$cell_type = factor(de_plot_sig$cell_type,levels=de_types)
de_plot_final = de_plot_sig %>% filter(gene%in%unique_genes)
de_plot_final$gene =  factor(de_plot_final$gene,levels=rev(grouped_ligands))
ggplot(de_plot_final,aes(x=cell_type,y=gene,fill=de)) +
    geom_tile() + theme_classic() + 
#     scale_fill_viridis(option="magma") +
    scale_fill_gradient2(low=muted("blue"),high=muted('red'))+
    xlab("Sender Cell Type") + ylab("Prioritized Ligands") + ggtitle("LogFold change of ligands in sender cells")+
    labs(fill="Log Fold\nChange")+
    theme(axis.text.x = element_text(angle=45,hjust=1,size=8),
         axis.text.y=element_text(size=8),legend.text=element_text(size=4),
         legend.title=element_text(size=8),plot.title=element_text(size=12),
         axis.title.y=element_text(size=12),axis.title.x=element_text(size=12)) 
dev.off()
```


```{r}
# Annotations
# Cell growth: "VEGFA","FGF23","NPNT"
# Cytokine: "TNFSF15","IFNG","CCL25","CXCL16"
# Immune extracellular membrane: "LTB","CD6","CD2","PTPRC","FASLG","CEACAM1"

```

















