---
title: "Szabo signatures"
output: html_notebook
---

```{r}
library(tidyverse)
library(Seurat)
library(progeny)
library(dorothea)
library(reshape2)
library(effsize)
library(viridis)

source("EE_vs_all_control_cohorts_analysis_helper_functions.R")
```

```{r}
combined = readRDS("durban_ee_eoe_resection_june152021.rds")
```


# Trm scoring

# Szabo scoring

```{r}
szabo_scores = read.csv("../reseq_analysis/figures/szabo_supp5.csv")
```

```{r}
tnk = subset(combined,tier1=="TNK") %>% subset(region=="Duodenum") %>% subset(HIV.HTLV.=="N")
```

```{r}
for(i in 1:ncol(szabo_scores)){
    print(colnames(szabo_scores)[i])
    tnk = AddModuleScore(tnk,features = list(as.character(szabo_scores[,i])),name = colnames(szabo_scores)[i],nbin=15)
}
```

```{r}
module_names = rep("",length(colnames(szabo_scores)))
for(i in 1:ncol(szabo_scores)){
    module_names[i] = paste0(colnames(szabo_scores)[i],"1")
} 
```


```{r}
sobj = subset(tnk,tier4 =="T CD8 CD69hi")
pvalues = rep(0,ncol(szabo_scores))
signs = rep(0,ncol(szabo_scores))
effects = rep(0,ncol(szabo_scores))
same_sign = rep(FALSE,ncol(szabo_scores))
for(i in 1:ncol(szabo_scores)){
    pvalues[i] = wilcox.test(sobj@meta.data[sobj$study=="EE",colnames(sobj@meta.data)==module_names[i]],sobj@meta.data[sobj$study!="EE",colnames(sobj@meta.data)==module_names[i]])$p.value
    
    effects[i] = cohen.d(sobj@meta.data[sobj$study=="EE",colnames(sobj@meta.data)==module_names[i]],sobj@meta.data[sobj$study!="EE",colnames(sobj@meta.data)==module_names[i]])$estimate

    median_ee = median(sobj@meta.data[sobj$study=="EE",colnames(sobj@meta.data)==module_names[i]])
    median_not_ee = median(sobj@meta.data[sobj$study!="EE",colnames(sobj@meta.data)==module_names[i]])
    signs[i] = median_ee - median_not_ee
    
    median_eoe = median(sobj@meta.data[sobj$study=="EoE",colnames(sobj@meta.data)==module_names[i]])
    median_wp = median(sobj@meta.data[sobj$study=="Resection",colnames(sobj@meta.data)==module_names[i]])
    median_sa = median(sobj@meta.data[sobj$study=="Durban",colnames(sobj@meta.data)==module_names[i]])
    
    eoe_diff = median_ee - median_eoe
    wp_diff = median_ee - median_wp
    sa_diff = median_ee - median_sa
    
    if(sign(eoe_diff)==sign(wp_diff) & sign(eoe_diff)==sign(sa_diff)){
        same_sign[i] = TRUE
    }

}
adj_pvals = p.adjust(pvalues,method="BH")
szabo_module_stats = data.frame(module=colnames(szabo_scores),adj_pvalue = adj_pvals,sign=signs,same_sign=same_sign,effect_size=effects)
szabo_module_stats = szabo_module_stats %>% filter(same_sign==TRUE) %>% filter(adj_pvalue< 0.05)
```

```{r}
saveRDS(szabo_module_stats,"szabo_scores.rds")
```

```{r}
szabo_module_stats
```


```{r}
disease_colors = readRDS("../reseq_analysis/disease_colors.rds")
disease_colors = c(disease_colors,"#fc9350")
```


```{r}
pdf("~/zambia_eed_figures/three_cohorts/tnk_figure/szabo_upreg.pdf",useDingbats = F,width=5,height=4)
tnk$study = factor(tnk$study,levels=c("EE","EoE","Resection","Durban"))
VlnPlot(tnk,c("CD8.Cytotoxic1","CD8.Cytokine1"),group.by="study",cols = disease_colors[c(1,3,4,5)],pt.size=.1)
dev.off()
```

# Trm signature scoring

```{r}
trm_signature = list(c("CD69","ITGAE","ITGA1","IL2","IL10","CXCR6",
                      "CXCL13","KCNK5","RGS1","CRTAM","DUSP6",
                       "PDCD1","IL23R"))
tnk = AddModuleScore(tnk,features = trm_signature,name="trm",nbin=15)

cell_types = unique(tnk$tier4)
pvalues = rep(0,length(cell_types))
for(i in 1:length(cell_types)){
    cell_type = cell_types[i]
    score = tnk$trm1[tnk$tier4==cell_type]
    not_score = tnk$trm1[tnk$tier4!=cell_type]
    pvalues[i] = wilcox.test(score,not_score,alternative = "greater")$p.value
}
adj = p.adjust(pvalues)
trm_pvalues = data.frame(cell_type=cell_types,pvalue=pvalues,adj_pval=adj)
```

```{r}
trm_pvalues
```


```{r}
# soring by pvalue
cells_by_pvalue = trm_pvalues$cell_type[order(trm_pvalues$pvalue)]
tnk$tier4 = factor(tnk$tier4,levels=cells_by_pvalue)

pdf("~/zambia_eed_figures/three_cohorts/tnk_figure/trm_scores_pls_work.pdf",useDingbats = F)
VlnPlot(tnk,"trm1",group.by="tier4",pt.size=0.1,cols = cell_type_colors) + 
    NoLegend() +
    theme(axis.text.x=element_text(angle=90)) +
    ggtitle("")+
    xlab("")+ylab("Module Score") + 
    geom_hline(yintercept=median(tnk$trm1), linetype="dashed")
dev.off()
```


